baseURL = "https://rei-ashine.github.io"
locale = "en-US"
title = "Rei ASHINE"
theme = "m10c"

[params]
		author = "Rei ASHINE"
		description = "\"The book called Life doesn't have the answers written at the back.\""
		avatar = "/images/avatar.png"
		menu_item_separator = "|"
		favicon = "/images/avatar.png"

		[[params.social]]
		icon = "github"
		name = "Github"
		url = "https://github.com/rei-ashine"

		[[params.social]]
		icon = "twitter"
		name = "Twitter"
		url = "https://x.com"

		[[params.social]]
    icon = "linkedin"
    name = "LinkedIn"
		url = "https://www.linkedin.com/in/Rei-Ashine"

		[params.analytics]
		gtm_id = "GTM-N348LCHN"
		# googleAnalytics = "G-XXXXXXXXXX" # GTMを使用するためこちらはコメントアウトのままにします

		[params.style]
		# https://www.colordic.org/w
		# Sidebar background color (白花色)
		darkestColor = "#e8ecef"
		# Main background color (白)
		darkColor = "#ffffff"
		# Theme color (山吹色)
		primaryColor = "#f8b500"
		# Font color for the title (褐返)
		lightestColor = "#203744"
		# Font color for the body (漆黒)
		lightColor = "#0d0015"

[[menu.main]]
identifier = "home"
name = "Home"
url = "/"

[[menu.main]]
identifier = "posts"
name = "Posts"
url = "/posts/"

[[menu.main]]
identifier = "tags"
name = "Tags"
url = "/tags/"
